
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: contacts
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin@123
      DB_NAME: contacts
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  postgres_data: